// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBercpZnWu1yjsaGCRtHVp5DrIutL6TqYE',
    appId: '1:1075959029127:web:590e626f8a83fbb8dec722',
    messagingSenderId: '1075959029127',
    projectId: 'contact-84af8',
    authDomain: 'contact-84af8.firebaseapp.com',
    databaseURL: 'https://contact-84af8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'contact-84af8.appspot.com',
    measurementId: 'G-R96B9ZHNN6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpw4idMsP26fxzmF4KtDf6peTV34GG5i0',
    appId: '1:1075959029127:android:1c8857a28b17ff9adec722',
    messagingSenderId: '1075959029127',
    projectId: 'contact-84af8',
    databaseURL: 'https://contact-84af8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'contact-84af8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDNvPbTsJ7508pI1t83JygP2sGWY7NE4c',
    appId: '1:1075959029127:ios:178d94827435ebd5dec722',
    messagingSenderId: '1075959029127',
    projectId: 'contact-84af8',
    databaseURL: 'https://contact-84af8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'contact-84af8.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDNvPbTsJ7508pI1t83JygP2sGWY7NE4c',
    appId: '1:1075959029127:ios:178d94827435ebd5dec722',
    messagingSenderId: '1075959029127',
    projectId: 'contact-84af8',
    databaseURL: 'https://contact-84af8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'contact-84af8.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBercpZnWu1yjsaGCRtHVp5DrIutL6TqYE',
    appId: '1:1075959029127:web:0975cff5560bb8bcdec722',
    messagingSenderId: '1075959029127',
    projectId: 'contact-84af8',
    authDomain: 'contact-84af8.firebaseapp.com',
    databaseURL: 'https://contact-84af8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'contact-84af8.appspot.com',
    measurementId: 'G-6PNPLW43F1',
  );

}