// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjRhNVFahztwTKnyJ_S5nytUg88J73LuY',
    appId: '1:262443037842:web:22e52f964f6d0f6a66624b',
    messagingSenderId: '262443037842',
    projectId: 'notes-63b1c',
    authDomain: 'notes-63b1c.firebaseapp.com',
    storageBucket: 'notes-63b1c.appspot.com',
    measurementId: 'G-HRN0PGLVFB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwoMAH01inGIgVlzTzaTandtQhftpv1iE',
    appId: '1:262443037842:android:ae774bc45e84e04d66624b',
    messagingSenderId: '262443037842',
    projectId: 'notes-63b1c',
    storageBucket: 'notes-63b1c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALXhEAT94c4QT4gekkahVDvUDGwQfE4i0',
    appId: '1:262443037842:ios:2631aef05d688dea66624b',
    messagingSenderId: '262443037842',
    projectId: 'notes-63b1c',
    storageBucket: 'notes-63b1c.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALXhEAT94c4QT4gekkahVDvUDGwQfE4i0',
    appId: '1:262443037842:ios:2631aef05d688dea66624b',
    messagingSenderId: '262443037842',
    projectId: 'notes-63b1c',
    storageBucket: 'notes-63b1c.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjRhNVFahztwTKnyJ_S5nytUg88J73LuY',
    appId: '1:262443037842:web:6028c4cd691bacc566624b',
    messagingSenderId: '262443037842',
    projectId: 'notes-63b1c',
    authDomain: 'notes-63b1c.firebaseapp.com',
    storageBucket: 'notes-63b1c.appspot.com',
    measurementId: 'G-CT5XJBMC5Q',
  );

}